# Netflix data analysis

## Libraries

In [1]:
import pandas as pd

## Load data

In [2]:
df = pd.read_csv('netflix_titles.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

## Data transformation

In [3]:
# Sort table by release_year 
df.sort_values('release_year', ascending=False, inplace=True)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2327,s2328,TV Show,Gabby's Dollhouse,NaN,"Laila Lockhart Kraner, Tucker Chandler, Juliet...",NaN,"January 5, 2021",2021,TV-Y,1 Season,Kids' TV,"Cute cats, quirky crafts and colorful magic! J..."
4468,s4469,TV Show,Night Stalker: The Hunt for a Serial Killer,Tiller Russell,NaN,NaN,"January 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries",Beneath the sunlit glamour of 1985 LA lurks a ...
2753,s2754,TV Show,History of Swear Words,NaN,Nicolas Cage,United States,"January 5, 2021",2021,TV-MA,1 Season,"Docuseries, TV Comedies","Nicolas Cage hosts this proudly profane, funny..."
5103,s5104,Movie,Ratones Paranoicos: The Band that Rocked Argen...,"Alejandro Ruax, Ramiro Martínez","Juan Sebastián Gutiérrez, Pablo Cano, Pablo Me...",NaN,"January 6, 2021",2021,TV-MA,76 min,"Documentaries, International Movies, Music & M...","The irrepressible Ratones Paranoicos, Argentin..."
1355,s1356,Movie,Chris Rock Total Blackout: The Tamborine Exten...,Chris Rock,Chris Rock,NaN,"January 12, 2021",2021,TV-MA,98 min,Stand-Up Comedy,"In this extended cut of his 2018 special, Chri..."
...,...,...,...,...,...,...,...,...,...,...,...,...
7616,s7617,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

In [4]:
# Fill in missing data
df['director'].fillna('Unknow', inplace=True)
df['country'].fillna('Unknow', inplace=True)

## German cinematography

### Fully German productions

In [5]:
# Select fully German productions released after 2010 
german_productions_full_df = df[(df['country'] == 'Germany') & (df['release_year'] > 2010)]
german_productions_full_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4388,s4389,TV Show,Nailed It! Germany,Unknow,"Angelina Kirsch, Bernd Siefert",Germany,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
4711,s4712,TV Show,Over Christmas,Unknow,"Luke Mockridge, Seyneb Saleh, Cristina do Rego...",Germany,"November 27, 2020",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Down-and-out musician Bastian battles the blue...
931,s932,TV Show,Biohackers,Unknow,"Luna Wedler, Jessica Schwarz, Adrian Julius Ti...",Germany,"August 20, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...",A medical student enters a top German universi...
3879,s3880,Movie,Making Unorthodox,Marlene Melchior,NaN,Germany,"March 26, 2020",2020,TV-G,21 min,"Documentaries, International Movies",A look at the making of one of the first serie...
672,s673,TV Show,Babylon Berlin,Unknow,"Volker Bruch, Liv Lisa Fries, Peter Kurth, Leo...",Germany,"March 1, 2020",2020,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A Soviet freight train's hijacking leads a hau...
5622,s5623,TV Show,Sing On! Germany,Unknow,Palina Rojinski,Germany,"August 7, 2020",2020,TV-PG,1 Season,"International TV Shows, Reality TV",In this karaoke competition hosted by Palina R...
841,s842,Movie,"Berlin, Berlin: Lolle on the Run",Franziska Meyer Price,"Felicitas Woll, Janina Uhse, Jan Sosniok, Matt...",Germany,"August 7, 2020",2020,TV-MA,82 min,"Comedies, International Movies","In this cinematic sequel to the hit TV series,..."
731,s732,TV Show,Barbarians,Unknow,"Laurence Rupp, Jeanne Goursaud, David Schütter...",Germany,"October 23, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,...",Torn between the mighty empire that raised him...
5220,s5221,Movie,Rising High,Cüneyt Kaya,"David Kross, Frederick Lau, Janina Uhse, Anne ...",Germany,"April 17, 2020",2020,TV-MA,95 min,"Dramas, International Movies","Ready to do anything to get rich, a young man ..."
2261,s2262,TV Show,Frank Elstner: Just One Last Question,Unknow,"Klaas Heufer-Umlauf, Joko Winterscheidt, Lena ...",Germany,"June 12, 2020",2020,TV-MA,1 Season,"International TV Shows, Stand-Up Comedy & Talk...","In his farewell show, legendary German host Fr..."
2267,s2268,Movie,Freaks – You're One of Us,Felix Binder,"Cornelia Gröschel, Tim Oliver Schultz, Wotan W...",Germany,"September 2, 2020",2020,TV-MA,93 min,"Dramas, Independent Movies, International Movies","Tipped by a mysterious tramp, a meek fry cook ..."
2145,s2146,Movie,Felix Lobrecht: Hype,Jan-Peter Horns,Felix Lobrecht,Germany,"November 3, 2020",2020,TV-MA,60 min,Stand-Up Comedy,Felix Lobrecht aims his dark humor at overly p...
3546,s3547,Movie,Latte and the Magic Waterstone,"Regina Welker, Nina Wels","Ashley Bornancin, Carter Hastings",Germany,"July 31, 2020",2020,TV-Y,83 min,"Children & Family Movies, Comedies",When a greedy bear steals a magic stone to kee...
1363,s1364,Movie,Christmas Crossfire,Detlev Buck,"Kostja Ullmann, Alli Neumann, Sascha Alexander...",Germany,"December 4, 2020",2020,TV-MA,106 min,"Comedies, International Movies, Thrillers","A man foils an attempted murder, then flees th..."
2664,s2665,Movie,Hazel Brugger: Tropical,Unknow,Hazel Brugger,Germany,"December 2, 2020",2020,TV-MA,58 min,Stand-Up Comedy,"In this stand-up special, comedian Hazel Brugg..."
3067,s3068,Movie,Isi & Ossi,Oliver Kienle,"Lisa Vicari, Dennis Mojen, Walid Al-Atiyat, Ch...",Germany,"February 14, 2020",2020,TV-MA,113 min,"Comedies, International Movies, Romantic Movies",A billionaire's daughter fakes a relationship ...
2849,s2850,TV Show,How to Sell Drugs Online (Fast),Unknow,"Maximilian Mundt, Danilo Kamperidis, Lena Klen...",Germany,"July 21, 2020",2020,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Com...","To win back his ex-girlfriend, a nerdy teen st..."
6573,s6574,TV Show,The Last Word,Unknow,"Anke Engelke, Thorsten Merten, Nina Gummich, J...",Germany,"September 17, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Comedies, TV Dramas","Suddenly a widow, a woman rekindles her thirst..."
7355,s7356,TV Show,Unorthodox,Unknow,"Shira Haas, Amit Rahav, Jeff Wilbusch, Alex Re...",Germany,"March 26, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas",A Hasidic Jewish woman in Brooklyn flees to Be...
213,s214,TV Show,A Perfect Crime,Unknow,NaN,Germany,"September 25, 2020",2020,TV-14,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries investigates the 1991 killing ...
5952,s5953,Movie,System Crasher,Nora Fingscheidt,"Helena Zengel, Albrecht Schuch, Gabriela Maria...",Germany,"February 21, 2020",2020,TV-MA,120 min,"Dramas, Independent Movies, International Movies","Traumatized, violent and yearning for love, 9-..."
7500,s7501,TV Show,We Are the Wave,Unknow,"Ludwig Simon, Luise Befort, Michelle Barthel, ...",Germany,"November 1, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A mysterious classmate leads four idealistic t...
2774,s2775,TV Show,Holiday Secrets,Unknow,"Corinna Harfouch, Christiane Paul, Svenja Jung...",Germany,"November 20, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Dramas",A Christmas reunion becomes a gateway to the p...
5241,s5242,Movie,Rock My Heart,Hanno Olderdissen,"Lena Klenke, Dieter Hallervorden, Emilio Sakra...",Germany,"June 7, 2019",2019,TV-PG,110 min,"Children & Family Movies, Dramas, Internationa...",After an adventurous teen with a heart defect ...
5658,s5659,TV Show,Skylines,Unknow,"Edin Hasanovic, Peri Baumeister, Murathan Musl...",Germany,"September 27, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A hip-hop producer gets hurled into the violen...
3372,s3373,Movie,Kidnapping Stella,Thomas Sieben,"Max von der Groeben, Jella Haase, Clemens Schick",Germany,"July 12, 2019",2019,TV-MA,90 min,"Dramas, International Movies, Thrillers","Snatched off the street and held for ransom, a..."
424,s425,Movie,Alles ist gut,Eva Trobisch,"Aenne Schwarz, Andreas Döhler, Hans Löw, Tilo ...",Germany,"June 6, 2019",2019,TV-MA,90 min,"Dramas, International Movies",A woman sexually assaulted by her new boss's b...
1539,s1540,TV Show,Criminal: Germany,Unknow,"Eva Meckbach, Sylvester Groth, Florence Kasumb...",Germany,"September 20, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","In the interview room, detectives go head-to-h..."
842,s843,Movie,"Berlin, I Love You",Unknow,NaN,Germany,"June 8, 2019",2019,R,120 min,"Dramas, International Movies, Romantic Movies","Set in the Grey City, this ""Cities of Love"" in..."
5206,s5207,Movie,Right Here Right Now,Jakob Lass,"Niklas Bruhn, David Schütter, Tinka Furst, Cor...",Germany,"June 16, 2019",2018,TV-MA,91 min,"Comedies, Dramas, Independent Movies",The owner of a failing music club throws one l...
4829,s4830,TV Show,Perfume,Unknow,"Friederike Becht, August Diehl, Wotan Wilke Mö...",Germany,"December 21, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","When a singer is found murdered, with her scen..."
1797,s1798,TV Show,Dogs of Berlin,Unknow,"Felix Kramer, Fahri Yardim, Anna Maria Mühe, K...",Germany,"December 7, 2018",2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Two cops investigate the murder of a famous Tu...
2007,s2008,Movie,Enissa Amani: Ehrenwort,Max Amini,Enissa Amani,Germany,"April 26, 2018",2018,TV-MA,66 min,Stand-Up Comedy,"Live from Hamburg, Iranian-German comedian Eni..."
3708,s3709,Movie,Lommbock,Christian Zübert,"Lucas Gregorowicz, Moritz Bleibtreu, Louis Hof...",Germany,"November 9, 2018",2017,TV-MA,106 min,"Comedies, International Movies","After finding love in drug-free Dubai, Stefan ..."
897,s898,Movie,Bibi & Tina: Tohuwabohu Total,Detlev Buck,"Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...",Germany,"December 27, 2017",2017,TV-14,106 min,"Children & Family Movies, Music & Musicals",Teen witch Bibi and her pal Tina return to the...
2103,s2104,Movie,Familiye,"Sedat Kirtan, Kubilay Sarikaya","Kubilay Sarikaya, Arnel Taci, Muhammed Kirtan,...",Germany,"May 1, 2019",2017,TV-MA,99 min,"Dramas, Independent Movies, International Movies",An ex-con struggles to take care of his two br...
1277,s1278,TV Show,Charité,Unknow,"Alicia von Rittberg, Maximilian Meyer-Bretschn...",Germany,"April 19, 2018",2017,TV-MA,1 Season,"International TV Shows, TV Dramas","At Berlin's Charité hospital in 1888, Ida find..."
2066,s2067,Movie,Expedition Happiness,Selima Taibi,"Selima Taibi, Felix Starck",Germany,"January 31, 2018",2017,TV-PG,96 min,"Documentaries, International Movies",A filmmaker and his musician girlfriend attemp...
1863,s1864,Movie,Dream Boat,Tristan Ferland Milewski,NaN,Germany,"December 1, 2017",2017,TV-MA,92 min,"Documentaries, International Movies, LGBTQ Movies","On a cruise for gay men, five passengers of di..."
5434,s5435,Movie,Schubert In Love,Lars Büchel,"Olaf Schubert, Mario Adorf, Marie Leuenberger,...",Germany,"March 1, 2018",2016,TV-14,94 min,"Comedies, International Movies","The last of his family line, Olaf Schubert doe..."
4840,s4841,Movie,Pettersson and Findus 2,Ali Samadi Ahadi,"Stefan Kurt, Marianne Sägebrecht, Max Herbrechter",Germany,"November 1, 2017",2016,TV-G,82 min,"Children & Family Movies, Comedies","Christmas is just around the corner, but Pette..."
1753,s1754,Movie,Dieter Nuhr: Nuhr in Berlin,Volker Weicker,Dieter Nuhr,Germany,"November 15, 2016",2016,TV-MA,69 min,Stand-Up Comedy,The cerebral and popular German cabaret comic ...
2287,s2288,Movie,Friend Request,Simon Verhoeven,"Alycia Debnam-Carey, William Moseley, Connor P...",Germany,"April 18, 2018",2016,R,92 min,"Horror Movies, International Movies",A popular college student's love of social med...
6712,s6713,Movie,The NSU-Complex,"Stefan Aust, Dirk Laabs",NaN,Germany,"December 28, 2016",2016,TV-14,90 min,"Documentaries, International Movies","For 13 years, the underground neo-Nazi organiz..."
1592,s1593,Movie,Dancing Quietly,Philipp Eichholtz,"Martina Schöne-Radunski, Hans-Heinrich Hardt, ...",Germany,"April 1, 2017",2016,TV-MA,70 min,"Dramas, Independent Movies, International Movies","After years of battling a deep depression, a y..."
4546,s4547,TV Show,NSU German History X,Unknow,"Anna Maria Mühe, Albrecht Schuch, Sebastian Ur...",Germany,"July 7, 2016",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","After German reunification, the neo-Nazi Natio..."
4580,s4581,Movie,Offline - Das leben ist kein bonuslevel,Florian Schnell,"Moritz Jahn, Mala Emde, Ugur Ekeroglu, David S...",Germany,"September 1, 2017",2016,TV-MA,89 min,"Action & Adventure, Comedies, International Mo...",Competitive gamer Jan finds his life thrown fo...
896,s897,Movie,Bibi & Tina: Girls Versus Boys,Detlev Buck,"Lina Larissa Strahl, Lisa-Marie Koroll, Tilman...",Germany,"April 15, 2017",2016,TV-14,107 min,"Children & Family Movies, Music & Musicals","At summer camp, young Bibi and her friends are..."
4808,s4809,Movie,Pedal the World,Felix Starck,Felix Starck,Germany,"June 1, 2018",2015,TV-MA,85 min,"Documentaries, International Movies, Sports Mo...",Over the course of one memorable and adventure...
102,s103,Movie,3 Türken & ein Baby,Sinan Akkuş,"Kostja Ullmann, Eko Fresh, Kida Khodr Ramadan,...",Germany,"December 15, 2016",2015,TV-MA,93 min,"Comedies, International Movies",The lives of three dissatisfied brothers runni...
3718,s3719,Movie,Look Who's Back,David Wnendt,"Oliver Masucci, Fabian Busch, Christoph Maria ...",Germany,"April 9, 2016",2015,NR,116 min,"Comedies, International Movies",When Adolf Hitler reawakens at the site of his...
185,s186,Movie,A Heavy Heart,Thomas Stuber,"Peter Kurth, Lena Lauzemis, Lina Wendel, Edin ...",Germany,"February 15, 2017",2015,TV-MA,109 min,"Dramas, Independent Movies, International Movies","Long past his heyday, a still-virile boxer tri..."
5813,s5814,Movie,Stereo,Maximilian Erlenwein,"Jürgen Vogel, Moritz Bleibtreu, Petra Schmidt-...",Germany,"January 15, 2017",2014,TV-MA,91 min,"International Movies, Thrillers",Erik's peaceful rural family life is shaken by...
7501,s7502,Movie,We Are Young. We Are Strong.,Burhan Qurbani,"Jonas Nay, Trang Le Hong, Devid Striesow, Joel...",Germany,"January 15, 2017",2014,TV-MA,123 min,"Dramas, International Movies","In 1992, three radically different residents o..."
894,s895,Movie,Bibi & Tina,Detlev Buck,"Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...",Germany,"April 15, 2017",2014,TV-PG,97 min,"Children & Family Movies, Music & Musicals",Teen witch Bibi and horse-loving Tina face tro...
895,s896,Movie,Bibi & Tina II,Detlev Buck,"Lina Larissa Strahl, Lisa-Marie Koroll, Louis ...",Germany,"April 15, 2017",2014,TV-14,105 min,"Children & Family Movies, Music & Musicals","When robbers hit Falkenstein castle, teen witc..."
6756,s6757,Movie,The Physician,Philipp Stölzl,"Tom Payne, Ben Kingsley, Stellan Skarsgård, Ol...",Germany,"July 15, 2015",2013,R,155 min,"Action & Adventure, Dramas, International Movies",A medical apprentice in 11th-century Persia di...
780,s781,Movie,Beak & Brain: Genius Birds From Down Under,"Volker Arzt, Angelika Sigl",NaN,Germany,"March 1, 2017",2013,TV-G,52 min,"Documentaries, International Movies","Whoever came up with the term ""bird brain"" nev..."

### All German productions

In [6]:
# Select all German productions released after 2010 
german_productions_all_df = df[(df['country'].str.contains('Germany')) & (df['release_year'] > 2010)]
german_productions_all_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4388,s4389,TV Show,Nailed It! Germany,Unknow,"Angelina Kirsch, Bernd Siefert",Germany,"January 17, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Home cooks try – and inevitably fail – to re-c...
4481,s4482,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,"Spain, Germany, Denmark, United States","January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
4601,s4602,TV Show,Oktoberfest: Beer & Blood,Unknow,"Mišel Matičević, Martina Gedeck, Klaus Steinba...","Germany, Czech Republic","October 1, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas","In 1900 Munich, ambitious brewer Curt Prank us..."
4711,s4712,TV Show,Over Christmas,Unknow,"Luke Mockridge, Seyneb Saleh, Cristina do Rego...",Germany,"November 27, 2020",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Down-and-out musician Bastian battles the blue...
4577,s4578,Movie,Offering to the Storm,Fernando González Molina,"Marta Etura, Leonardo Sbaraglia, Carlos Librad...","Spain, Germany","July 24, 2020",2020,TV-MA,140 min,"International Movies, Thrillers",Amaia investigates several suspicious infant d...
...,...,...,...,...,...,...,...,...,...,...,...,...
2300,s2301,Movie,Frozen Planet: On Thin Ice,Unknow,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,47 min,Movies,David Attenborough journeys to both polar regi...
2299,s2300,TV Show,Frozen Planet,Alastair Fothergill,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...",Go on a journey through the Arctic and Antarct...
5960,s5961,Movie,Take Me Home Tonight,Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...","United States, Germany","May 16, 2019",2011,R,97 min,"Comedies, Romantic Movies","Set in the financial boom of the late 1980s, t..."
7351,s7352,Movie,Unknown,Jaume Collet-Serra,"Liam Neeson, Diane Kruger, January Jones, Aida...","United Kingdom, Germany, France, United States","January 1, 2021",2011,PG-13,113 min,"Action & Adventure, Thrillers",Liam Neeson stars as a man who regains conscio...
1808,s1809,Movie,Don 2,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Boman Irani, ...","India, Germany","December 15, 2019",2011,TV-14,148 min,"Action & Adventure, International Movies, Musi...","With Asia under his complete control, criminal..."

### Productions with German participation

In [7]:
german_productions_participation_df = german_productions_all_df.merge(german_productions_full_df[['show_id', 'title']], on='show_id', how='left')
german_productions_participation_df = german_productions_participation_df[german_productions_participation_df['title_y'].isnull()]\
                                                                                                        .drop('title_y', axis='columns')\
                                                                                                        .rename({'title_x' : 'title'}, axis='columns')
german_productions_participation_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s4482,TV Show,"Nisman: The Prosecutor, the President, and the...",Justin Webster,NaN,"Spain, Germany, Denmark, United States","January 1, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",This docuseries details the suspicious death o...
2,s4602,TV Show,Oktoberfest: Beer & Blood,Unknow,"Mišel Matičević, Martina Gedeck, Klaus Steinba...","Germany, Czech Republic","October 1, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas","In 1900 Munich, ambitious brewer Curt Prank us..."
4,s4578,Movie,Offering to the Storm,Fernando González Molina,"Marta Etura, Leonardo Sbaraglia, Carlos Librad...","Spain, Germany","July 24, 2020",2020,TV-MA,140 min,"International Movies, Thrillers",Amaia investigates several suspicious infant d...
9,s4838,Movie,Pets United,Reinhard Klooss,"Patrick Roche, Natalie Dormer, Eddie Marsan, F...","Germany, China, United Kingdom","September 11, 2020",2020,TV-Y7,93 min,"Children & Family Movies, Comedies",A street-smart dog and a pampered cat join for...
15,s2285,TV Show,Freud,Unknow,"Robert Finster, Ella Rumpf, Georg Friedrich, C...","Austria, Germany","March 23, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","Eager to make his name in 19th-century Vienna,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
149,s2301,Movie,Frozen Planet: On Thin Ice,Unknow,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,47 min,Movies,David Attenborough journeys to both polar regi...
150,s2300,TV Show,Frozen Planet,Alastair Fothergill,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...",Go on a journey through the Arctic and Antarct...
151,s5961,Movie,Take Me Home Tonight,Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...","United States, Germany","May 16, 2019",2011,R,97 min,"Comedies, Romantic Movies","Set in the financial boom of the late 1980s, t..."
152,s7352,Movie,Unknown,Jaume Collet-Serra,"Liam Neeson, Diane Kruger, January Jones, Aida...","United Kingdom, Germany, France, United States","January 1, 2021",2011,PG-13,113 min,"Action & Adventure, Thrillers",Liam Neeson stars as a man who regains conscio...
153,s1809,Movie,Don 2,Farhan Akhtar,"Shah Rukh Khan, Priyanka Chopra, Boman Irani, ...","India, Germany","December 15, 2019",2011,TV-14,148 min,"Action & Adventure, International Movies, Musi...","With Asia under his complete control, criminal..."

## Swedish cinematography

In [8]:
# Show all productions where Sweden was only country or main country of production (listed as first)
mainly_sweden_films = df.copy()

mainly_sweden_films['main_country'] = mainly_sweden_films['country'].apply(lambda x: x.split(',')[0] if ',' in x else x)

mainly_sweden_films = mainly_sweden_films[mainly_sweden_films['main_country'] == 'Sweden']
mainly_sweden_films

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,main_country
3741,s3742,TV Show,Love & Anarchy,Unknow,"Ida Engvoll, Björn Mosten, Carla Sehn, Reine B...",Sweden,"November 4, 2020",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A married consultant and a young IT tech kick ...,Sweden
1634,s1635,Movie,David Batra: Elefanten i rummet,"David Batra, Jon Rudberg",David Batra,Sweden,"April 1, 2020",2020,TV-MA,77 min,Stand-Up Comedy,Swedish comedian David Batra gets personal as ...,Sweden
1178,s1179,TV Show,Caliphate,Unknow,"Aliette Opheim, Gizem Erdogan, Amed Bozan, Alb...",Sweden,"March 18, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas",An impending ISIS attack on Sweden entangles a...,Sweden
5040,s5041,TV Show,Quicksand,Unknow,"Hanna Ardéhn, Felix Sandman, William Spetz, El...",Sweden,"April 5, 2019",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",After a tragedy at a school sends shock waves ...,Sweden
3629,s3630,Movie,Life Overtakes Me,"John Haptas, Kristine Samuelson",NaN,"Sweden, United States","June 15, 2019",2019,TV-PG,40 min,Documentaries,"In the grip of trauma, hundreds of refugee chi...",Sweden
1042,s1043,TV Show,Bonus Family,Unknow,"Vera Vitali, Erik Johansson, Fredrik Hallgren,...",Sweden,"July 12, 2019",2019,TV-MA,3 Seasons,"International TV Shows, TV Dramas","A new couple, their exes and their children na...",Sweden
636,s637,Movie,Avicii: True Stories,Levan Tsikurishvili,Avicii,"Sweden, Netherlands","December 28, 2018",2017,TV-MA,97 min,"Documentaries, International Movies, Music & M...","Follow the meteoric rise of Tim Bergling, aka ...",Sweden
6686,s6687,TV Show,The Most Beautiful Hands of Delhi,Unknow,"Björn Kjellman, Joy Sengupta, Natasha Jayetileke",Sweden,"July 20, 2017",2017,TV-MA,1 Season,"International TV Shows, TV Comedies, TV Dramas","A stalled career, failed marriage and receding...",Sweden
2098,s2099,TV Show,Fallet,Unknow,"Lisa Henni, Adam Godley, Tomas von Brömssen, L...",Sweden,"April 1, 2018",2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Com...",A Swedish detective and her timid British coll...,Sweden
2907,s2908,Movie,I Called Him Morgan,Kasper Collin,NaN,"Sweden, United States","July 24, 2017",2016,TV-14,91 min,"Documentaries, Music & Musicals",Decades after serving a prison sentence for ki...,Sweden
3108,s3109,Movie,Jag älskar dig: En skilsmässokomedi,Johan Brisinger,"Björn Kjellman, Christine Meltzer, Rodolfo Cor...",Sweden,"March 15, 2018",2016,TV-MA,91 min,"Comedies, Dramas, International Movies","Tired of her passionless marriage, Marianne wa...",Sweden
2376,s2377,TV Show,Gentlemen and Gangsters,Unknow,"David Dencik, Ruth Vega Fernandez, David Fukam...",Sweden,"June 1, 2016",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Romant...","Now on the run, a writer relates his previous ...",Sweden
401,s402,Movie,Alive and Kicking,Susan Glatzer,NaN,"Sweden, United States","August 10, 2017",2016,TV-14,89 min,Documentaries,Take an inside look at swing dancing's continu...,Sweden
6048,s6049,Movie,The 101-Year-Old Man Who Skipped Out on the Bi...,"Felix Herngren, Måns Herngren","Robert Gustafsson, Jens Hultén, Caroline Boult...",Sweden,"April 25, 2017",2016,TV-MA,108 min,"Comedies, International Movies","In need of money, an eccentric ex-spy and his ...",Sweden
5450,s5451,Movie,Searching for Sugar Man,Malik Bendjelloul,Rodriguez,"Sweden, United Kingdom, Finland","December 1, 2019",2012,PG-13,86 min,"Documentaries, International Movies, Music & M...",Decades after Detroit singer-songwriter Rodrig...,Sweden
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,Sweden

## Cinematic productions by country and year (pivot table)

In [9]:
# Support table (preview)
grouped_df = df.groupby(['type', 'release_year'])\
                ['show_id'].count().reset_index()
grouped_df

        type  release_year  show_id
0      Movie          1942        2
1      Movie          1943        3
2      Movie          1944        3
3      Movie          1945        3
4      Movie          1946        1
..       ...           ...      ...
113  TV Show          2017      268
114  TV Show          2018      387
115  TV Show          2019      414
116  TV Show          2020      457
117  TV Show          2021       19

[118 rows x 3 columns]

In [10]:
# Clean values of date_added columns and change type to datetime
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])

In [11]:
# Group DataFrame by type and release_year 
# Count show_id and show min date_added 
grouped_df = df.groupby(['type', 'release_year'])\
               .agg({'show_id': 'count', 
                     'date_added': 'min'})
print(grouped_df.to_string())

                      show_id date_added
type    release_year
Movie   1942                2 2017-03-31
        1943                3 2017-03-31
        1944                3 2017-03-31
        1945                3 2017-03-31
        1946                1 2017-03-31
        1947                1 2017-03-31
        1954                2 2020-06-18
        1955                3 2019-11-01
        1956                2 2019-11-01
        1958                3 2019-11-01
        1959                1 2017-10-15
        1960                4 2017-10-15
        1962                3 2017-07-01
        1963                1 2020-06-18
        1964                1 2019-12-31
        1965                2 2019-11-01
        1966                1 2017-07-01
        1967                4 2019-07-01
        1968                4 2019-11-01
        1969                2 2017-06-01
        1970                2 2019-10-01
        1971                5 2017-04-01
        1972                3 2019-11-01
        1973               10 2016-11-01
        1974                6 2017-09-01
        1975                6 2017-04-01
        1976                9 2017-09-01
        1977                6 2017-02-10
        1978                6 2017-11-01
        1979               10 2016-12-01
        1980                9 2017-12-01
        1981                8 2016-11-01
        1982               15 2018-08-16
        1983                9 2017-09-01
        1984                9 2017-09-01
        1985                8 2018-07-15
        1986                8 2011-10-01
        1987                7 2010-11-01
        1988               14 2011-10-01
        1989               12 2011-10-01
        1990               17 2011-10-01
        1991               16 2011-10-01
        1992               16 2016-11-01
        1993               18 2017-06-01
        1994               15 2016-08-01
        1995               17 2017-05-15
        1996               16 2017-05-01
        1997               26 2018-03-01
        1998               27 2016-11-01
        1999               26 2017-12-15
        2000               30 2011-09-27
        2001               32 2017-03-10
        2002               39 2017-09-01
        2003               40 2016-12-20
        2004               50 2017-03-10
        2005               61 2016-03-16
        2006               72 2008-01-01
        2007               72 2009-05-05
        2008              102 2016-01-15
        2009              103 2009-11-18
        2010              136 2011-05-17
        2011              127 2012-02-21
        2012              158 2012-11-14
        2013              202 2013-09-01
        2014              244 2014-01-24
        2015              382 2015-01-23
        2016              642 2016-01-08
        2017              744 2017-01-03
        2018              734 2017-07-01
        2019              582 2018-10-26
        2020              411 2020-01-01
        2021               12 2021-01-01
TV Show 1925                1 2018-12-30
        1946                1 2017-02-01
        1963                1 2017-07-01
        1967                1 2017-07-01
        1968                1 2017-10-01
        1972                1 2018-10-02
        1974                1 2018-10-02
        1977                1 2018-03-31
        1979                1 2017-12-31
        1981                1 2018-12-23
        1985                1 2016-10-01
        1986                2 2019-01-10
        1988                2 2016-11-01
        1989                1 2016-05-22
        1990                3 2014-12-18
        1991                1 2016-06-01
        1992                2 2015-06-15
        1993                4 2018-04-02
        1994                1 2016-12-01
        1995                2 2016-01-01
        1996                3 2016-01-01
        1997                4 2014-11-19
        1998                4 2014-11-19
        1999                7 2016-01-01
        2000                4 2016-01-01
        2001                4 2015-10-10
        2002                6 2016-01-01
        2003                9 2016-01-01
        2004                9 2016-01-01
        2005               12 2015-12-25
        2006               13 2015-04-22
        2007               13 2008-02-04
        2008               23 2016-01-01
        2009               34 2015-04-22
        2010               37 2016-01-01
        2011               39 2015-03-15
        2012               61 2013-10-08
        2013               65 2013-08-02
        2014               90 2014-11-21
        2015              159 2015-05-22
        2016              240 2013-03-31
        2017              268 2016-12-13
        2018              387 2016-12-23
        2019              414 2018-05-29
        2020              457 2019-10-11
        2021               19 2020-12-14

In [12]:
# Create pivot DataFrame: show_id count by release_year and main_country
df['main_country'] = df['country'].apply(lambda x: x.split(',')[0] if ',' in x else x)
country_year_pivot_df = pd.pivot_table(df, columns='release_year', index='main_country', values='show_id', aggfunc='count')

# Fill missing data with 0
# Reverse columns order and change type to int
country_year_pivot_df = country_year_pivot_df.fillna(0)
country_year_pivot_df = country_year_pivot_df[reversed(country_year_pivot_df.columns)].astype(int)

# Add column sum (sum of rows) and sort values by new column
country_year_pivot_df['sum'] = country_year_pivot_df.sum(axis='columns')
country_year_pivot_df = country_year_pivot_df.sort_values('sum', ascending=False)#.drop('sum', axis='columns')

country_year_pivot_df

release_year,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,1955,1954,1947,1946,1945,1944,1943,1942,1925,sum
main_country,,,,,,,,,,,,,,,,,,,,,
United States,13,350,387,376,378,285,164,99,92,78,...,1,1,1,2,3,3,3,2,0,2883
India,1,66,89,100,104,75,66,53,54,36,...,0,0,0,0,0,0,0,0,0,956
United Kingdom,2,59,50,78,85,88,50,31,21,17,...,0,0,0,0,0,0,0,0,0,577
Unknow,9,63,97,100,54,62,39,19,10,11,...,0,0,0,0,0,0,0,0,1,507
Canada,1,35,25,46,40,40,21,18,3,5,...,0,0,0,0,0,0,0,0,0,259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Guatemala,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Greece,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Cyprus,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Belarus,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Zimbabwe,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## Movies average duration by country and year (pivot table)

In [13]:
df['duration']

2327    1 Season
4468    1 Season
2753    1 Season
5103      76 min
1355      98 min
          ...
7616      82 min
7342      61 min
6117      18 min
4960      52 min
4867    1 Season
Name: duration, Length: 7787, dtype: object

In [14]:
# Select needed columns
# Filter only movies
# Extract the duration (minutes)
task_df = df[['type', 'release_year', 'main_country', 'duration']]
task_df = task_df[task_df['type'] == 'Movie'].reset_index(drop=True)
task_df['duration'] = task_df['duration'].apply(lambda x: int(x.split(' ')[0]))

# Create pivot DataFrame: average movie duration by release_year and main_country
# Fill in missing data with 0
pivot_df = pd.pivot_table(task_df, columns='release_year', index='main_country', values='duration', aggfunc='mean')
pivot_df = pivot_df.fillna(0)

# Reverse columns order and change type to int
pivot_df = pivot_df[reversed(pivot_df.columns)].astype(int)

pivot_df

release_year,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,1958,1956,1955,1954,1947,1946,1945,1944,1943,1942
main_country,,,,,,,,,,,,,,,,,,,,,
Argentina,0,99,88,75,90,92,101,0,85,0,...,0,0,0,0,0,0,0,0,0,0
Australia,0,84,106,97,85,82,98,105,111,92,...,0,0,0,0,0,0,0,0,0,0
Austria,0,93,101,89,99,112,0,98,0,0,...,0,0,0,0,0,0,0,0,0,0
Bangladesh,0,0,0,115,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Belgium,0,0,0,102,0,107,77,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uruguay,0,72,74,98,76,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Venezuela,0,0,0,0,119,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Vietnam,0,93,97,0,0,116,92,112,0,0,...,0,0,0,0,0,0,0,0,0,0
West Germany,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Zimbabwe,0,0,0,0,100,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0